name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up pip cache directory
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: ./.televenv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-venv-


      - name: Install dependencies
        run: |
          python -m venv .televenv
          .\.televenv\Scripts\python.exe -m pip install --upgrade pip
          .\.televenv\Scripts\python.exe -m pip install -r requirements.txt

      - name: Confirm Python version
        run: .\.televenv\Scripts\python.exe --version

      - name: Run Black formatting check
        run: .\.televenv\Scripts\black . --check --diff

      - name: Run pytest
        run: .\.televenv\Scripts\python.exe -m pytest tests --maxfail=1 --disable-warnings -q
